### ISSUE TITLE
Detect duplicate hostnames config/systems.yaml

### ISSUE THREAD

**Issue by behlendorf** [NearNodeFlash/nnf-deploy#53]
When deploying a configuration with multiple rabbits `nnf-deploy` does not generate an error if  the same compute hostname is used for multiple rabbits.  It would be nice to be able to immediately detect this kind of configuration error.  For example:

```
systems:
  rabbits:
    rabbit0: { 0: b0, 1: bp1, 2: bp2, ... }
    rabbit1: { 0: b0, 1: bp17, 2: bp18, ... }
               ^^^^^
```
